name: flutter_inappwebview_designhubz_internal_annotations
description: Internal annotations used by the generator of flutter_inappwebview_designhubz plugin
version: 1.1.1
homepage: https://github.com/pichillilorenzo/flutter_inappwebview_designhubz

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  test: ^1.21.6